name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: docker-hub

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker buildx build \
        -t andreacicca/pdflatex:latest \
        --platform linux/amd64,linux/arm64 \
        --push \
        .

    - name: Set date variable
      run: echo "DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV

    - name: building andreacicca/pdflatex:date
      run: |
        docker buildx build \
        -t andreacicca/pdflatex:${{ env.DATE }} \
        --platform linux/amd64,linux/arm64 \
        --push \
        .